name: Node.js CI/CD with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Use Node.js v20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Enable caching for dependencies

      - name: Install Dependencies
        run: npm install --force # Faster & ensures clean install

      - name: Build Application
        run: npm run build --if-present

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }} # Use access token instead of password

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-api:v1.0.1 .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-api:v1.0.1

  deploy_to_server:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: docker # Now waits for the Docker build to complete

    steps:
      - name: Trigger Webhook Deployment
        uses: distributhor/workflow-webhook@v2 
        env:
          webhook_url: https://h1test.invoicemate.net/webhooks/node-api
          webhook_secret: none
